### ISSUE TITLE
VP8 not being forwarded

### ISSUE THREAD

**Issue by arekm** [01org/intel-hybrid-driver#18]
libva-1.6.1-1.x86_64
libva-driver-intel-1.6.1-1.x86_64
libva-driver-intel-hybrid-1.0.1-1.x86_64
libcmrt-1.0.5-1.x86_64

```
[arekm@xps ~]$ vainfo |grep VP
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/libva/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
      VAProfileVP9Profile0            : VAEntrypointVLD
[arekm@xps ~]$ LIBVA_DRIVER_NAME=hybrid vainfo |grep VP
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'hybrid'
libva info: Trying to open /usr/lib64/libva/dri/hybrid_drv_video.so
libva info: Found init function __vaDriverInit_0_34
libva info: va_openDriver() returns 0
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
```

VAProfileVP8Version0_3 is not being forwarded when using via regular intel driver while VAProfileVP9Profile0 is forwarded nicely. Not sure if this is a bug though. I assume it is.

**Comment by seanvk** [comment]
It's intentional.  VP8 Hybrid Encode is really only supported on one platform, Baytrail.  So we don't expose it more generally.

**Comment by Ristovski** [comment]
@seanvk is this still the case? Same bug is still present but I can see Haswell bits in the vp8 encoder
