### ISSUE TITLE
libva error: hybrid_drv_video.so has no function __vaDriverInit_1_0

### ISSUE THREAD

**Issue by ghost** [01org/intel-hybrid-driver#24]
I'm trying to build this for libva 2.0.0 but even after rebuilding all packages against the new version of libva trying to run vainfo with LIBVA_DRIVER_NAME=hybrid results in the following output:

`libva info: VA-API version 1.0.0`
`libva info: va_getDriverName() returns 0`
`libva info: User requested driver 'hybrid'`
`libva info: Trying to open /usr/lib/dri/hybrid_drv_video.so`
`libva error: /usr/lib/dri/hybrid_drv_video.so has no function __vaDriverInit_1_0`
`libva info: va_openDriver() returns -1`
`vaInitialize failed with error code -1 (unknown libva error),exit`

Running
`nm --demangle -D /usr/lib/dri/hybrid_drv_video.so | grep vaDriver`
Shows that there is still a reference to the previous version of libva
`000000000001c610 T __vaDriverInit_0_34`

**Comment by skrisna** [comment]
How did you solve the issue? I am getting the same error. Thanks!

**Comment by gallee** [comment]
Same here. If you found out how to solve it, I am interested !
